# Generated by Django 3.2.6 on 2021-10-13 20:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=45)),
                ('business_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('first_suscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 12, 16, 16, 44, 362334))),
                ('expired', models.BooleanField(default=False)),
                ('suscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
