# Generated by Django 3.2.6 on 2021-10-22 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_suscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscribed',
            name='valid_to',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 21, 8, 15, 4, 250367)),
        ),
    ]
