# Generated by Django 3.1.5 on 2021-10-26 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0009_alter_suscribed_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscribed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suscribed',
            name='valid_to',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 24, 22, 59, 16, 898341)),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
