# Generated by Django 3.1.5 on 2021-10-26 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0010_auto_20211025_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscribed',
            name='valid_to',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 24, 23, 0, 48, 782343)),
        ),
    ]
