# Generated by Django 3.2.6 on 2021-11-02 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0013_alter_suscribed_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscribed',
            name='valid_to',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 2, 19, 42, 30, 746010)),
        ),
    ]
