# Generated by Django 3.2.6 on 2021-11-15 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0015_alter_suscribed_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscribed',
            name='areas_suscribed',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='suscribed',
            name='valid_to',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 15, 7, 26, 4, 257853)),
        ),
    ]
