# Generated by Django 3.2.6 on 2021-11-16 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0016_auto_20211115_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscribed',
            name='valid_to',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 16, 16, 36, 31, 259105)),
        ),
    ]
