# Generated by Django 3.2.6 on 2021-11-23 23:28

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0018_alter_suscribed_valid_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suscribed',
            old_name='bussiness_name',
            new_name='business_name',
        ),
        migrations.AlterField(
            model_name='suscribed',
            name='business_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='suscribed',
            name='valid_to',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 23, 19, 28, 17, 907876)),
        ),
    ]
