# Generated by Django 3.2.6 on 2021-11-23 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0019_auto_20211123_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscribed',
            name='expired',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='suscribed',
            name='valid_to',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 23, 19, 40, 30, 75665)),
        ),
    ]
