# Generated by Django 3.1.5 on 2021-10-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_fila', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mi_fila',
            name='place_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mi_fila',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
