# Generated by Django 3.2.6 on 2021-10-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_fila', '0002_auto_20211025_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi_fila',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
