# Generated by Django 3.2.6 on 2021-11-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_fila', '0004_rename_place_id_mi_fila_persona_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mi_fila',
            name='area_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
