# Generated by Django 3.2.6 on 2021-11-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_fila', '0005_mi_fila_area_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mi_fila',
            name='persona_id',
        ),
    ]
