# Generated by Django 3.2.6 on 2021-10-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('premium', '0012_auto_20211028_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=45)),
                ('place_id', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.suscribed')),
            ],
        ),
    ]
