# Generated by Django 3.2.6 on 2021-11-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner_areas',
            old_name='place_id',
            new_name='area_id',
        ),
        migrations.AddField(
            model_name='owner_areas',
            name='current_position',
            field=models.IntegerField(default=0),
        ),
    ]
