# Generated by Django 3.2.6 on 2021-11-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0016_auto_20211115_0726'),
        ('management', '0002_auto_20211102_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_employee', models.CharField(max_length=45)),
                ('employee_user', models.CharField(max_length=24)),
                ('employee_passcode', models.PositiveIntegerField(unique=True)),
                ('fila_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.suscribed')),
            ],
        ),
    ]
