# Generated by Django 3.2.6 on 2021-11-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_passcode',
        ),
    ]
