# Generated by Django 3.2.6 on 2021-11-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_employee_employee_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_areas',
            name='current_position',
            field=models.IntegerField(default=1),
        ),
    ]
